import z from "zod"
import { GroupManagement } from "@/lib/group-management"
import { CommandsCollection } from "@/lib/managed-commands"
import { fmt } from "@/utils/format"
import type { Role } from "@/utils/types"

export const groups = new CommandsCollection<Role>("Groups")
  .createCommand({
    trigger: "updategroup",
    scope: "private",
    description: "Trigger group info update to the database (eg. title or tag change)",
    args: [
      {
        key: "chatId",
        optional: false,
        type: z.coerce.number(),
        description: "Chat ID (number, obtained from alternative clients) of the group you want to force update",
      },
    ],
    permissions: {
      allowedRoles: ["owner", "direttivo"],
    },
    handler: async ({ context, args }) => {
      const group = await context.api.getChat(args.chatId).catch(() => null)
      if (!group) {
        await context.reply(
          fmt(
            ({ code, n }) =>
              n`Group with chatId ${code`${args.chatId}`} does not exists or the bot is not an administrator.`
          )
        )
        return
      }

      if (group.type === "private") {
        await context.reply(
          fmt(({ code, n }) => n`Chat with chatId ${code`${args.chatId}`} is a private chat, not a group.`)
        )
        return
      }

      const res = await GroupManagement.update(group.id, context.from)
      if (res.isErr()) {
        await context.reply(
          fmt(({ code, n, b, i }) => [b`There was an ERROR`, n`chatId: ${code`${args.chatId}`}`, i`\n${res.error}`], {
            sep: "\n",
          })
        )
        return
      }

      await context.reply(
        fmt(({ code, n, b }) => [b`✅ Group Updated`, n`chatId: ${code`${args.chatId}`}`], {
          sep: "\n",
        })
      )
    },
  })
  .createCommand({
    trigger: "regenerate_group_links",
    scope: "private",
    description: "Revoke and regenerate every stored Telegram group invite link",
    args: [
      {
        key: "confirmation",
        optional: false,
        type: z.literal("confirm"),
        description: 'Type "confirm" to rotate all group links',
      },
    ],
    permissions: {
      allowedRoles: ["owner", "direttivo"],
    },
    handler: async ({ context }) => {
      const response = await GroupManagement.regenerateInviteLinks(context.from)
      if (response.alreadyRunning) {
        await context.reply(fmt(({ n }) => n`A group link regeneration is already running.`))
        return
      }
      if ("error" in response) {
        await context.reply(
          fmt(({ b, n }) => [b`❌ Group link regeneration aborted`, n`${response.error}`], { sep: "\n" })
        )
        return
      }

      const { result } = response
      await context.reply(
        fmt(
          ({ b, n, code }) => [
            result.failures.length === 0
              ? b`✅ Group link regeneration completed`
              : b`⚠️ Group link regeneration completed with errors`,
            n`${b`Groups found:`} ${code`${result.total}`}`,
            n`${b`Links regenerated by Telegram:`} ${code`${result.regenerated}`}`,
            n`${b`Links synchronized to the backend:`} ${code`${result.synchronized}`}`,
            n`${b`Failures:`} ${code`${result.failures.length}`}`,
            result.failures.length > 0
              ? n`Check the Group Management topic and application logs for failure details.`
              : undefined,
          ],
          { sep: "\n" }
        )
      )
    },
  })
