// import "./test"
import "./mute"
import "./ban"
import "./kick"
import "./del"
import "./role"
import "./userid"
import "./link-admin-dashboard"

export { _commandsBase as commands } from "./_base"
