import "./test"
import "./mute"
import "./audit"
import "./ban"
import "./banall"
import "./kick"
import "./del"
import "./search"
import "./role"
import "./userid"
import "./link-admin-dashboard"
import "./report"
import "./grants"

export { _commandsBase as commands } from "./_base"
