name: Docker Image CI
on:
  push:
    branches: ["main"]
    paths:
      - "**.ts"
      - "**.tsx"
      - "package.json"
      - "tsconfig.json"
      - "tsconfig.*.json"
      - "pnpm-lock.yaml"
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/polinetworkorg/telegram:latest
