name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          # version: 10 # not set because it's specified in package.json -> packageManager field
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Check Format
        run: pnpm run format:check
