name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  test:
    name: Typecheck and Lint
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          # version: 10 # not set because it's specified in package.json -> packageManager field
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Unit Test
        run: pnpm run test
      - name: Typecheck
        run: pnpm run typecheck
      - name: Run Biome
        run: pnpm exec biome ci .
